#!/usr/bin/env php
<?php

$autoloads = array(
    "vendor/autoload.php",
    __DIR__ . "/vendor/autoload.php",
    dirname(__DIR__) . "/vendor/autoload.php",
    dirname(dirname(__DIR__)) . "/vendor/autoload.php",
);

foreach ($autoloads as $autoload) {
    if (file_exists($autoload)) {
        require_once $autoload;
    }
}

use Seven\OneskyDownloader\Application;

$config = array(
    'onesky_api_key'    => getenv('ONESKY_APIKEY'),
    'onesky_api_secret' => getenv('ONESKY_APISECRET'),
    'onesky_project'    => getenv('ONESKY_PROJECT'),
);

$app = new Application($config);
$app->addCommands(array(
    new Seven\OneskyDownloader\Command\DownloadCommand(),
));

$app->run();
